name: Build Android APK

on:
  workflow_dispatch: # Allows manual trigger from the GitHub Actions UI

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: 'app/package-lock.json'

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Install dependencies
        working-directory: ./app
        run: npm install

      - name: Create google-services.json
        working-directory: ./app        
        run: |
          cat << 'EOF' > google-services.json
          ${{ secrets.GOOGLE_SERVICES_JSON }}
          EOF

      - name: Run Expo Prebuild
        working-directory: ./app
        run: npx expo prebuild --platform android --clean

      - name: Build APK
        working-directory: ./app/android
        run: ./gradlew assembleRelease

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Android-APK
          path: app/android/app/build/outputs/apk/release/app-release.apk
          retention-days: 7
